export const fonts = {
    'AntDesign': require('../../assets/fonts/AntDesign.ttf'),
    'Feather': require('../../assets/fonts/Feather.ttf'),
    'FontAwesome': require('../../assets/fonts/FontAwesome.ttf'),
    'Entypo': require('../../assets/fonts/Entypo.ttf'),
    'EvilIcons': require('../../assets/fonts/EvilIcons.ttf'),
    'FontAwesome5_Brands': require('../../assets/fonts/FontAwesome5_Brands.ttf'),
    'FontAwesome5_Regular': require('../../assets/fonts/FontAwesome5_Regular.ttf'),
    'FontAwesome5_Solid': require('../../assets/fonts/FontAwesome5_Solid.ttf'),
    'Fontisto': require('../../assets/fonts/Fontisto.ttf'),
    'Foundation': require('../../assets/fonts/Foundation.ttf'),
    'Ionicons': require('../../assets/fonts/Ionicons.ttf'),
    'MaterialCommunityIcons': require('../../assets/fonts/MaterialCommunityIcons.ttf'),
    'MaterialIcons': require('../../assets/fonts/MaterialIcons.ttf'),
    'Octicons': require('../../assets/fonts/Octicons.ttf'),
    'SimpleLineIcons': require('../../assets/fonts/SimpleLineIcons.ttf'),
    'Zocial': require('../../assets/fonts/Zocial.ttf'),
}